# Generated by Django 4.1.5 on 2023-01-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_goldprice_date_added"),
        ("orders", "0002_alter_orderdetails_product_alter_orders_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("price", models.FloatField(blank=True, default=0)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="date",
            new_name="date_added",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="products",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="totalcost",
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Placed", "Orderplaced"),
                    ("Creating", "creating"),
                    ("Completed", "completed"),
                    ("Shipped", "shipped"),
                ],
                default="Order Placed",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="OrderDetails",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="map_order",
                to="orders.orders",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="map_product",
                to="products.price",
            ),
        ),
    ]
