# Generated by Django 4.1.5 on 2023-01-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_rename_date_orders_date_added_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="account",
            new_name="users",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AddField(
            model_name="orders",
            name="transaction_id",
            field=models.CharField(default=23456, max_length=255),
            preserve_default=False,
        ),
    ]
