# Generated by Django 3.2.2 on 2021-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='harammodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haramcode', models.CharField(max_length=100)),
                ('haramimg', models.ImageField(upload_to='harams')),
                ('haramweight', models.IntegerField()),
            ],
        ),
    ]
