# Generated by Django 3.2.2 on 2021-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prcjapp', '0002_auto_20210522_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='harammodels',
            name='haram_fav_status',
            field=models.BooleanField(default=False),
        ),
    ]
