# Generated by Django 3.2.2 on 2021-06-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prcjapp', '0008_item_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_models',
            old_name='itemid',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='item_models',
            old_name='itemtype',
            new_name='item_type',
        ),
    ]
