# Generated by Django 4.1.5 on 2023-01-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_goldprice_date_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="price",
        ),
    ]
