# Generated by Django 4.1.5 on 2023-01-31 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_price_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goldprice",
            options={"verbose_name_plural": "GoldPrice"},
        ),
        migrations.AlterModelOptions(
            name="price",
            options={"verbose_name_plural": "Price"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name_plural": "Category"},
        ),
        migrations.AlterField(
            model_name="price",
            name="gold_price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price",
                to="products.goldprice",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price",
                to="products.products",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.category",
            ),
        ),
    ]
