# Generated by Django 4.1.5 on 2023-01-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_users_date_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name_plural": "Users"},
        ),
    ]
