# Generated by Django 3.2.2 on 2021-05-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prcjapp', '0003_harammodels_haram_fav_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='banglemodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bangle_id', models.CharField(max_length=100)),
                ('bangle_image', models.ImageField(upload_to='bangles')),
                ('bangle_weight', models.IntegerField()),
                ('bangle_fav_status', models.BooleanField(default=False)),
            ],
        ),
    ]
