# Generated by Django 3.2.2 on 2021-05-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prcjapp', '0005_chainsmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='chainmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chains_id', models.CharField(max_length=100)),
                ('chains_image', models.ImageField(upload_to='chains')),
                ('chains_weight', models.IntegerField()),
                ('chains_fav_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='chainsmodels',
        ),
    ]
