# Generated by Django 3.2.2 on 2021-06-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prcjapp', '0007_login_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=100)),
                ('itemtype', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to='allmodels')),
                ('item_weight', models.IntegerField()),
                ('item_status', models.BooleanField(default=False)),
            ],
        ),
    ]
