# Generated by Django 4.1.5 on 2023-01-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_products_alter_order_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="account",
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
