# Generated by Django 4.1.5 on 2023-01-29 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="price",
        ),
        migrations.AlterField(
            model_name="products",
            name="weight",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fixed_value", models.FloatField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="catalog.products",
                    ),
                ),
            ],
        ),
    ]
