# Generated by Django 4.1.5 on 2023-01-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_products_price_alter_products_weight_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gold", models.FloatField(default=1927.32)),
            ],
        ),
        migrations.RemoveField(
            model_name="price",
            name="fixed_value",
        ),
        migrations.AddField(
            model_name="price",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price",
                to="catalog.products",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="gold_price",
            field=models.ForeignKey(
                default=1927.32,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goldPrice",
                to="catalog.goldprice",
            ),
            preserve_default=False,
        ),
    ]
