# Generated by Django 4.1.5 on 2023-01-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_goldprice_remove_price_fixed_value_price_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="type",
            field=models.CharField(
                choices=[("gold", "Gold"), ("silver", "Silver")],
                default="Gold",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="price",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
